[workspace]
resolver = "3"
members = ["lychee", "crates/*"]

[workspace.package]
version = "1.0.0"
edition = "2024"

[workspace.dependencies]
pound = "0.1.6"
iced = { version = "0.14.0", features = ["image", "wayland", "smol", "canvas"] }
iced_graphics = "0.14.0"
image = "0.25.10"

lychee-cli = { path = "./crates/lychee-cli" }
lychee-img = { path = "./crates/lychee-img" }
lychee-core = { path = "./crates/lychee-core" }
lychee-widgets = { path = "./crates/lychee-widgets" }

[profile.release]
lto = true
codegen-units = 1
strip = true
